### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by mikezhang3679** [googlesamples/android-Camera2Raw#15]
![image](https://user-images.githubusercontent.com/15795338/39244907-b5c055ce-48c4-11e8-9b0e-968bfffaea17.png)

crash on Android 8.1.0

**Comment by vipulasri** [comment]
same error on Android 7.1.1, Moto G4 plus

**Comment by isVoid** [comment]
Same error Sony G8142 Android 9, API28
```
2019-03-02 09:50:50.744 18572-18572/com.example.android.camera2raw E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.camera2raw, PID: 18572
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.hardware.camera2.CameraCharacteristics.get(android.hardware.camera2.CameraCharacteristics$Key)' on a null object reference
        at com.example.android.camera2raw.Camera2RawFragment.configureTransform(Camera2RawFragment.java:1046)
        at com.example.android.camera2raw.Camera2RawFragment.access$000(Camera2RawFragment.java:121)
        at com.example.android.camera2raw.Camera2RawFragment$1.onSurfaceTextureAvailable(Camera2RawFragment.java:212)
...
```

**Comment by isVoid** [comment]
In fact, I think this problem results from the device does not support RAW photography. I suggest downloading an app called "OpenCamera" and check device info to find out if your device supports RAW shooting. 

lgyjg's fork addresses this crash.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
