### ISSUE TITLE
Crashing out on emulator and device 

### ISSUE THREAD

**Issue by sononix** [googlesamples/android-Camera2Raw#2]
06-17 05:02:37.210    4348-4348/com.example.android.camera2raw D/AndroidRuntime﹕ Shutting down VM
06-17 05:02:37.213    4348-4348/com.example.android.camera2raw E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.example.android.camera2raw, PID: 4348
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.hardware.camera2.CameraCharacteristics.get(android.hardware.camera2.CameraCharacteristics$Key)' on a null object reference
            at com.example.android.camera2raw.Camera2RawFragment.configureTransform(Camera2RawFragment.java:940)
            at com.example.android.camera2raw.Camera2RawFragment.access$000(Camera2RawFragment.java:116)
            at com.example.android.camera2raw.Camera2RawFragment$1.onSurfaceTextureAvailable(Camera2RawFragment.java:181)
            at android.view.TextureView.getHardwareLayer(TextureView.java:370)
            at android.view.View.updateDisplayListIfDirty(View.java:14144)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.View.draw(View.java:14959)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14162)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.View.draw(View.java:14959)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.draw(View.java:15234)
            at android.widget.FrameLayout.draw(FrameLayout.java:598)
            at android.view.View.updateDisplayListIfDirty(View.java:14167)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.View.draw(View.java:14959)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14162)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.View.draw(View.java:14959)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14162)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.View.draw(View.java:14959)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.draw(View.java:15234)
            at android.widget.FrameLayout.draw(FrameLayout.java:598)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2650)
            at android.view.View.updateDisplayListIfDirty(View.java:14167)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
            at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
            at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2530)
            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2352)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1982)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:550)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by ajithmemana** [comment]
I am also getting the same issue with the sample.

**Comment by workpanda** [comment]
12244-12244/com.example.android.camera2video E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.example.android.camera2video, PID: 12244
    java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
            at com.example.android.camera2video.Camera2VideoFragment.openCamera(Camera2VideoFragment.java:347)
            at com.example.android.camera2video.Camera2VideoFragment.access$000(Camera2VideoFragment.java:62)
            at com.example.android.camera2video.Camera2VideoFragment$1.onSurfaceTextureAvailable(Camera2VideoFragment.java:105)
            at android.view.TextureView.getHardwareLayer(TextureView.java:370)
            at android.view.View.updateDisplayListIfDirty(View.java:14144)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.View.draw(View.java:14959)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14162)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.View.draw(View.java:14959)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.draw(View.java:15234)
            at android.widget.FrameLayout.draw(FrameLayout.java:598)
            at android.view.View.updateDisplayListIfDirty(View.java:14167)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.View.draw(View.java:14959)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14162)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.View.draw(View.java:14959)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14162)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.View.draw(View.java:14959)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.draw(View.java:15234)
            at android.widget.FrameLayout.draw(FrameLayout.java:598)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2650)
            at android.view.View.updateDisplayListIfDirty(View.java:14167)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
            at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
            at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2530)
            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2352)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1982)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:550)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5257)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by workpanda** [comment]
I am getting errors above when launching the app of googlesamples/android-Camera2Video.

**Comment by juliooa** [comment]
For the OP problem I was having the same error and it was because my phone doesn't have the RAW capability, meaning the CameraCharacteristics.REQUEST_AVAILABLE_CAPABILITIES_RAW (https://developer.android.com/reference/android/hardware/camera2/CameraMetadata.html#REQUEST_AVAILABLE_CAPABILITIES_RAW), so the mCharacteristics is never set.
You can remove all the RAW references and implementations and it should work.

**Comment by IgorGanapolsky** [comment]
This crash happens on devices that don't support capturing RAW photos.  I opened  PR https://github.com/googlesamples/android-Camera2Raw/pull/5  to circumvent the app crash by showing an ErrorDialog:
![device-2015-11-08-111232](https://cloud.githubusercontent.com/assets/201209/11021260/ae8dbd44-8609-11e5-8b6b-f7c220bcfc84.png)

**Comment by lgyjg** [comment]
I am also getting the same crash:

```
10-12 17:58:54.841 13484-13484/com.example.android.camera2raw E/AndroidRuntime: FATAL EXCEPTION: main
        Process: com.example.android.camera2raw, PID: 13484
        java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.hardware.camera2.CameraCharacteristics.get(android.hardware.camera2.CameraCharacteristics$Key)' on a null object reference
            at com.example.android.camera2raw.Camera2RawFragment.configureTransform(Camera2RawFragment.java:1046)
            at com.example.android.camera2raw.Camera2RawFragment.access$000(Camera2RawFragment.java:121)
            at com.example.android.camera2raw.Camera2RawFragment$1.onSurfaceTextureAvailable(Camera2RawFragment.java:212)
....
```
IS that means my devices doesn't support the raw capture?

**Comment by ghost** [comment]
It crashes for me on the emulator due to a null pointer exeption

**Comment by aman-jham** [comment]
Unable to run, its crashing while the time of opening it self, Please find the below log details

```
  java.lang.NullPointerException: 
Attempt to invoke virtual method 
'java.lang.Object android.hardware.camera2
.CameraCharacteristics
.get(android.hardware.camera2.CameraCharacteristics$Key)' 
on a null object reference                                      at com.example.android.camera2raw.Camera2RawFragment.configureTransform(Camera2RawFragment.java:1046)
                                                                                  at com.example.android.camera2raw.Camera2RawFragment.access$000(Camera2RawFragment.java:121)
                                                                                  at com.example.android.camera2raw.Camera2RawFragment$1.onSurfaceTextureAvailable(Camera2RawFragment.java:212)
```

**Comment by mkutlu** [comment]
I got same error on configureTransform method. Then I initialize characteristics with manager object. But this time I cant get preview because of "device is not supported raw" exception while working on vm

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
