### ISSUE TITLE
Does Not Run, null pointer exception

### ISSUE THREAD

**Issue by ghost** [googlesamples/android-Camera2Raw#20]
It appears mCharacteristics is null, indeed I don't believe it is EVER set, anywhere in the code, so not too surprising.

08-17 07:57:47.305 5598-5598/com.example.android.camera2raw E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.camera2raw, PID: 5598
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.hardware.camera2.CameraCharacteristics.get(android.hardware.camera2.CameraCharacteristics$Key)' on a null object reference
        at com.example.android.camera2raw.Camera2RawFragment.configureTransform(Camera2RawFragment.java:1046)
        at com.example.android.camera2raw.Camera2RawFragment.access$000(Camera2RawFragment.java:121)
        at com.example.android.camera2raw.Camera2RawFragment$1.onSurfaceTextureAvailable(Camera2RawFragment.java:212)
        at android.view.TextureView.getHardwareLayer(TextureView.java:390)
        at android.view.TextureView.draw(TextureView.java:339)
        at android.view.View.updateDisplayListIfDirty(View.java:16171)

**Comment by drkpoon** [comment]
The codes from line 711 to 715 check if camera has raw capability.  It seems that camera on your device does not have such capability.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
