### ISSUE TITLE
App crash on both device and AVD at startup

### ISSUE THREAD

**Issue by shadow-wxh** [googlesamples/android-Camera2Raw#23]
App crash on startup,can somebody confirm this code sample still maitained and workable?

11-25 08:01:57.511 27723-27723/? E/dalvikvm: >>>>> com.example.android.camera2basic [ userId:0 | appId:10268 ]
11-25 08:01:57.806 27723-27723/com.example.android.camera2basic E/dalvikvm: Could not find class 'com.example.android.camera2basic.Camera2BasicFragment$2', referenced from method com.example.android.camera2basic.Camera2BasicFragment.<init>
11-25 08:01:57.816 27723-27723/com.example.android.camera2basic E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.camera2basic, PID: 27723
    java.lang.VerifyError: com/example/android/camera2basic/Camera2BasicFragment
        at com.example.android.camera2basic.CameraActivity.onCreate(CameraActivity.java:30)
        at android.app.Activity.performCreate(Activity.java:5580)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2400)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495)
        at android.app.ActivityThread.access$900(ActivityThread.java:170)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1304)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:146)
        at android.app.ActivityThread.main(ActivityThread.java:5635)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by dnhyde** [comment]
Same issue here!

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
